In [45]:
import cv2 as cv
import matplotlib.pyplot as plt
import time

img_mat = cv.imread('demo.png')    ## BGR
cv.imwrite('demo_w.png',img_mat)   ## BGR

img_mat_shallow = img_mat.view() ## 浅拷贝
img_mat_deep = img_mat.copy() ## 深拷贝

b,g,r = cv.split(img_mat) ## 分割通道
img_mat_ = cv.merge((b,g,r)) ## 合并通道


def show_img_Window(img_mat,winName,waitTime=0,exitKey='q',ifDestroyAll=True):
    cv.imshow(winName, img_mat)
    while True:
        key = cv.waitKey(waitTime)
        if (key & 0xFF ==ord(exitKey)) or (key == -1):
            if ifDestroyAll:
                cv.destroyAllWindows()
            return key     ## exit via exitKey or via click/auto(-1)
        
def show_video_Window(winName,videoAddr,frameIntv=1000,exitKey='q'):  ## frameIntv:ms to show next frame
    cv.namedWindow(winName,cv.WINDOW_NORMAL)
    cam = cv.VideoCapture(videoAddr)       ## 0: camera
    while cam.isOpened():
        ret,frame_mat = cam.read()
        if not ret:
            print('cannot read frame..Break')
            break
        video_exit_key = show_img_Window(frame_mat,winName,waitTime=frameIntv,exitKey=exitKey,ifDestroyAll=False)
        if video_exit_key& 0xFF ==ord(exitKey):
            print('end..')
            break
    cam.release()
    cv.destroyAllWindows()

In [ ]:
show_img_Window(img_mat,'winName',waitTime=1000,exitKey='q',ifDestroyAll=True)

In [ ]:
show_video_Window('videoWin',0,frameIntv=1000,exitKey='q')

In [ ]:
time_intv = 1 ## second
frames = []

cam = cv.VideoCapture(0)   ## 0:Camera
while cam.isOpened():                     ## load
    ret,frame_mat = cam.read()
    if not ret:
        print('cannot read frame..Break')
        break
    time.sleep(time_intv)
    frames.append(frame_mat)
    print('show frame:{}'.format(len(frames)) )      ##  plot/window/save...
    if len(frames)>=5:             ## end video
        break

cam.release()

In [ ]:
fourcc = cv.VideoWriter_fourcc(*'mp4v')
vidWriter = cv.VideoWriter('demo.mp4',fourcc,1,(640,480))  ## file, fourcc, framePerSecond, (dim)[, isColor]
for frame_mat in frames:
    vidWriter.write(frame_mat)

vidWriter.release()

In [18]:
def mouse_callback(event,x,y,flags,userdata):  ## MouseEventNO.,x,y,KeyPressFlagsNO.,otherinputData
    print(event,x,y,flags,userdata)        ## e.g. 0,756,166,0,demo userdata  -- 0-EVENT_MOUSEMOVE & 
    
cv.namedWindow('myWin',cv.WINDOW_NORMAL)        ## Step1: new window
cv.setMouseCallback('myWin',mouse_callback,'demo userdata') ## Step2: set callback
show_img_Window(img_mat,'myWin',waitTime=0,exitKey='q')      ## Step3: open img in window

0 706 1 0 demo userdata


-1

In [15]:
def bar_callback(value):
    pass

cv.namedWindow('myWin',cv.WINDOW_NORMAL)              ## Step1: new window
cv.createTrackbar('barA','myWin',0,255,bar_callback)  ## Step2: new bar
while True:
    try:
        valA = cv.getTrackbarPos('barA','myWin')      ## opt: get current bar val
        show_img_Window(img_mat-valA,'myWin',waitTime=1,exitKey='q',ifDestroyAll=False)   ## Step3: open img in window
    except:
        break   

In [32]:
img_cvt = cv.cvtColor(img_mat,cv.COLOR_BGR2GRAY)
show_img_Window(img_cvt,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1

In [36]:
demo_mat = cv.line(img_mat,(0,0),(100,900),(0,0,0),2,8,0)
show_img_Window(demo_mat,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1

In [57]:
from PIL import ImageFont,ImageDraw,Image
import numpy as np

font = ImageFont.truetype('demo.ttc',15)
img_pillow = Image.fromarray(img_mat)
draw = ImageDraw.Draw(img_pillow)
draw.text((0,0),'这是一',font=font,fill=(0,0,255))   ## fill=color

img_CN = np.array(img_pillow)
show_img_Window(img_CN,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1

In [122]:
img_demo = cv.add(img_mat[1:10,1:10],-80)  
img_demo = img_mat[1:10,1:10]-255
img_demo

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
  

In [140]:
~255

-256

In [130]:
255 & 255

255

In [146]:
255 | 255

255

In [147]:
255 ^ 255

0

In [141]:
cv.bitwise_not(img_mat[1:10,1:10])

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
  

In [142]:
cv.bitwise_and(img_mat[1:10,1:10],img_mat[1:10,1:10])

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255

In [143]:
cv.bitwise_or(img_mat[1:10,1:10],img_mat[1:10,1:10])

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255

In [148]:
img_mat[1:10,1:10] ^ 255

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
  

In [155]:
img_rotate = img_rotate = cv.rotate(img_mat,2)

show_img_Window(img_rotate,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1

In [160]:
h,w,ch = img_mat.shape

src = np.float32([[11,11],[23,56],[99,88]])
dst = np.float32([[21,11],[33,56],[109,88]])
affM = cv.getAffineTransform(src,dst) 
img_affine = cv.warpAffine(img_mat,affM,(w,h))
show_img_Window(img_affine,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1

In [162]:
src = np.float32([[11,11],[23,56],[99,88],[199,88]])
dst = np.float32([[21,11],[33,56],[109,88],[209,88]])
M = cv.getPerspectiveTransform(src,dst) 
img_perspective = cv.warpPerspective(img_mat,M,(w,h))
show_img_Window(img_perspective,'myWin',waitTime=0,exitKey='q',ifDestroyAll=True)

-1